Porsche & Bentley patches
Enable navigation function for CN and JP
Enable CarLife automatically on CN FW. Feedback on functionality needed!
Add POG11 AndroidAuto button fix.
BYG24 widescreen CarPlay mode
PATCH AIO includes POG11 AA button fix & G24 CarPlay widescreen patch
various small improvements

diff --git a/apps/javag24 b/apps/javag24
--- a/apps/javag24
+++ b/apps/javag24
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-revision="javapog24 v0.1.1 (2022-03-13 MIB-Wiki)"
+revision="javag24 v0.2.0 (2022-06-12 MIB-Wiki)"
 # use --help for more info
 
 export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
@@ -21,7 +21,7 @@ if [ -f $TMP/backup.mib ] || [ -f $TMP/reboot.mib ] || [ -f $TMP/flash.mib ]; th
 fi
 
 APP="/net/mmx/mnt/app/eso/hmi/lsd/jars/"
-JAR="pog24fs.jar"
+JAR="g24ws.jar"
 
 case $1 in
 
@@ -30,8 +30,8 @@ case $1 in
 
 trap '' 2
 
-	echo -ne "Enable fullscreen CarPlay and AndroidAuto on POG24\n"
-	if [[ "$TRAINVERSION" = *POG24* ]]; then
+	echo -ne "Enable widescreen CarPlay and AndroidAuto on G24\n"
+	if [[ "$TRAINVERSION" = *POG24* ]] || [[ "$TRAINVERSION" = *BYG24* ]]; then
 		if [ -f $APP$JAR ]; then
 			echo -ne "File already present on unit. Will be replaced\n" | $TEE -a $LO
 		fi
@@ -49,19 +49,41 @@ return 2> /dev/null
 
 };;
 
+-onnr) {
+
+trap '' 2
+
+	echo -ne "Enable widescreen CarPlay and AndroidAuto on G24\n"
+	if [[ "$TRAINVERSION" = *POG24* ]] || [[ "$TRAINVERSION" = *BYG24* ]]; then
+		if [ -f $APP$JAR ]; then
+			echo -ne "File already present on unit. Will be replaced\n" | $TEE -a $LO
+		fi
+		mount -uw /net/mmx/mnt/app
+		cp -r $VOLUME/mod/java/$JAR $APP$JAR 2>> $LOG
+		mount -ur /net/mmx/mnt/app
+	else
+		echo -ne "no supported train found - will stop here\n" | $TEE -a $LOG
+	fi
+
+trap 2
+
+return 2> /dev/null
+
+};;
+
 -off) {
 
 trap '' 2
 
-	echo -ne "Remove fullscreen CarPlay and AndroidAuto support from POG24\n"
-	if [[ "$TRAINVERSION" = *POG24* ]]; then
+	echo -ne "Remove widescreen CarPlay and AndroidAuto support from G24\n"
+	if [[ "$TRAINVERSION" = *POG24* ]] || [[ "$TRAINVERSION" = *BYG24* ]]; then
 		if [ -f $APP$JAR ]; then
 			mount -uw /net/mmx/mnt/app
 			rm -rf $APP$JAR 2>> $LOG
 			mount -ur /net/mmx/mnt/app
 			. $thisdir/reboot -t 10
 		else
-				echo -ne "File not found - fullscreen patch is not installed\n" | $TEE -a $LOG
+				echo -ne "File not found - widescreen patch is not installed\n" | $TEE -a $LOG
 		fi
 	else
 		echo -ne "no supported train found - will stop here\n" | $TEE -a $LOG
@@ -81,8 +103,9 @@ return 2> /dev/null
 		echo "Usage: "$thisname" [OPTION]"
 		echo ""
 		echo "Options:"
-		echo "        -on 		enable CP/AA fullscreen support"
-		echo "        -off 		remove CP/AA fullscreen support"
+		echo "        -on 		enable CP/AA widescreen support"
+		echo "        -onnr 		enable CP/AA widescreen support - no reboot"
+		echo "        -off 		remove CP/AA widescreen support"
 		echo "        --help		show this help"
 		echo ""
 		echo "Note: Backup will only work in RCC bash!"
