merge and remove wrong file format

diff --git a/apps/NavActiveIgnore b/apps/NavActiveIgnore
--- a/apps/NavActiveIgnore
+++ b/apps/NavActiveIgnore
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-revision="NavActiveIgnore v0.1.0 (2022-03-13 MIB-Wiki)"
+revision="NavActiveIgnore v0.1.1 (2022-08-26 MIB-Wiki)"
 # Thanks to andrewleech for making this possible! https://github.com/jilleb/mib2-toolbox/pull/189
 # use --help for more info
 
@@ -23,30 +23,41 @@ fi
 
 APP="/net/mmx/mnt/app/eso/hmi/lsd/jars/"
 JAR="NavActiveIgnore.jar"
+LSD=/net/mmx/mnt/app/eso/hmi/lsd/lsd.sh
+BU=/net/mmx/mnt/app/eso/hmi/lsd/lsd.sh.bu
 
 case $1 in
-
 
 -on) {
 
 trap '' 2
 
-	echo -ne "Enabled NavActiveIgnore\n"
+	echo -ne "Enabled NavActiveIgnore\n" | $TEE -a $LOG
 	if [[ "$TRAINVERSION" = *VWG1* ]] || [[ "$TRAINVERSION" = *SKG1* ]] || [[ "$TRAINVERSION" = *SEG1* ]]; then
 		echo -ne "Please note, that this patch will only work on latest FW versions.\n"
-		echo -ne "Update FW before applying the patch.\n" 
+		echo -ne "Update FW before applying the patch.\n"
 		sleep 5
 		if [ -f $APP$JAR ]; then
-			echo -ne "File already present on unit. Will be replaced\n" | $TEE -a $LO
+			echo -ne "$JAR already present on unit. Will be replaced\n" | $TEE -a $LOG
 		fi
 		mount -uw /net/mmx/mnt/app
+		cp -r $LSD $BACKUPFOLDER/$MUVERSION-lsd.sh
 		cp -r $VOLUME/mod/java/$JAR $APP$JAR 2>> $LOG
-		mount -ur /net/mmx/mnt/app
+			if ! grep -q "Find and append jar files" ${LSD}; then
+				if [ ! -e $BU ]; then
+					echo "Backup lsd.sh" | $TEE -a $LOG
+					cp -v $LSD $BU 2>> $LOG
+				fi
+			echo "Patching lsd.sh to run additional *.jar" | $TEE -a $LOG
+			$SED -ir 's,^$J9,## Find and append jar files\nif [[ -d /net/mmx/mnt/app/eso/hmi/lsd/jars/ ]]; then\n	JARS=$(find /net/mmx/mnt/app/eso/hmi/lsd/jars/ -name '*.zip' -or -name '*.jar')\n	if [[ ! "x$JARS" == "x" ]]; then\n		for jar in $JARS; do\n			BOOTCLASSPATH="$BOOTCLASSPATH:$jar"\n		done\n	fi\nfi\n$J9,g' $LSD 2>> $LOG
+		else
+			echo "lsd.sh is already patched" | $TEE -a $LOG
+		fi
 		. $thisdir/reboot -t 10
-	else
-		echo -ne "no supported train found - will stop here\n" | $TEE -a $LOG
-		echo -ne "Audi/Porsche/Bentley are currently not supported by this patch.\n" 
-	fi
+		else
+			echo -ne "no supported train found - will stop here\n" | $TEE -a $LOG
+			echo -ne "Audi/Porsche/Bentley are currently not supported by this patch.\n"
+		fi
 
 trap 2
 
@@ -58,16 +69,21 @@ return 2> /dev/null
 
 trap '' 2
 
-	echo -ne "Remove NavActiveIgnore\n"
+	echo -ne "Remove NavActiveIgnore\n" | $TEE -a $LOG
 	if [[ "$TRAINVERSION" = *VWG1* ]] || [[ "$TRAINVERSION" = *SKG1* ]] || [[ "$TRAINVERSION" = *SEG1* ]]; then
+		mount -uw /net/mmx/mnt/app
 		if [ -f $APP$JAR ]; then
 			mount -uw /net/mmx/mnt/app
-			rm -rf $APP$JAR 2>> $LOG
-			mount -ur /net/mmx/mnt/app
-			. $thisdir/reboot -t 10
+			rm -rf $APP$JAR 2>> $LOG 2>> $LOG
+			echo "NavActiveIgnore.jar removed" | $TEE -a $LOG
 		else
-				echo -ne "File not found - fullscreen patch is not installed\n" | $TEE -a $LOG
+				echo -ne "File not found - navignore patch is not installed\n" | $TEE -a $LOG
 		fi
+		if [ -e $BU ]; then
+			mv -f $BU $LSD 2>> $LOG
+			echo "lsd.sh restored from backup" | $TEE -a $LOG
+		fi
+		. $thisdir/reboot -t 10
 	else
 		echo -ne "no supported train found - will stop here\n" | $TEE -a $LOG
 	fi
@@ -86,8 +102,8 @@ return 2> /dev/null
 		echo "Usage: "$thisname" [OPTION]"
 		echo ""
 		echo "Options:"
-		echo "        -on 		enable CP/AA fullscreen support"
-		echo "        -off 		remove CP/AA fullscreen support"
+		echo "        -on 		enable navignore"
+		echo "        -off 		remove navignore"
 		echo "        --help		show this help"
 		echo ""
 		echo "Note: Backup will only work in RCC bash!"
