Logic bugfixes and cleaner code

diff --git a/apps/setlang b/apps/setlang
--- a/apps/setlang
+++ b/apps/setlang
@@ -27,7 +27,7 @@ else
 fi
 
 #Get the real train not from GLOBALS but from EEPROM as it can be changed already
-TRAINVERSION="$(on -f rcc /net/rcc/usr/apps/modifyE2P r 3A0 19 | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )"
+TRAINVERSION="$($E2P r 3A0 19 | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )"
 
 DATASET_2D00=0
 DATASET_280=0
@@ -35,42 +35,46 @@ DATASET_280=0
 case $1 in
 	-eu) {
 		trap '' 2
-		if [[ "$TRAINVERSION" = *ER_VWG* ]] || [[ "$TRAINVERSION" = *ER_SKG* ]] || [[ "$TRAINVERSION" = *ER_SEG* ]]; then
-			echo -ne "Writing EU dataset 0x2D00 (visible_MMI_language_dataset):\n" | $TEE -a $LOG
-			echo -ne "de_DE,en_GB,fr_FR,it_IT,es_ES,nl_NL,cs_CZ,pt_PT,sv_SE,tr_TR,ru_RU,\n" | $TEE -a $LOG
-			echo -ne "pl_PL,no_NO,en_US,es_MX,pt_BR,ar_SA,bs_BA,ro_RO,sk_SK,sl_SI,sr_RS,\n" | $TEE -a $LOG
-			echo -ne "da_DK,el_GR, hr_HR,hu_HU,fi_FI,bg_BG,lv_LV,et_EE,lt_LT,uk_UA\n" | $TEE -a $LOG
-			DATASET_2D00=2064655F444503656E5F47420366725F46520169745F49540165735F4553016E6C5F4E4C0163735F435A0170745F50540173765F53450174725F54520272755F525501706C5F504C016E6F5F4E4F01656E5F55530165735F4D580170745F42520161725F53410162735F424101726F5F524F01736B5F534B01736C5F53490173725F52530164615F444B01656C5F47520168725F48520168755F48550166695F46490162675F4247016C765F4C560165745F4545016C745F4C5401756B5F554101656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F47420163735F435A01656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F47420172755F52550130336D01
-			echo -ne "Writing en_GB dataset 0x280 (language dataset)\n" | $TEE -a $LOG
-			DATASET_280=656E5F474200656E5F474200656E5F4742004331E45D
-		elif [[ "$TRAINVERSION" = *ER_POG* ]] || [[ "$TRAINVERSION" = *ER_BYSUV* ]]; then
-			echo -ne "Set visible_MMI_language_dataset - 0x2d00 - EU\n" | $TEE -a $LOG
-			echo -ne "de_DE,en_GB,en_SA,fr_FR,it_IT,es_ES,pt_PT,pt_BR,nl_NL,ru_RU,pl_PL,cs_CZ,es_MX,en_US,sv_SE,tr_TR,hu_HU,no_NO,ar_SA,el_GR,fi_FI,hr_HR,da_DK,sl_SI,sk_SK,sr_RS,ro_RO,bs_BA\n"
-			DATASET_2D00=2064655F444503656E5F47420366725F46520169745F49540165735F4553016E6C5F4E4C0163735F435A0170745F50540173765F53450174725F54520272755F525501706C5F504C016E6F5F4E4F01656E5F55530165735F4D580170745F42520161725F53410162735F424101726F5F524F01736B5F534B01736C5F53490173725F52530164615F444B01656C5F47520168725F48520168755F48550166695F46490162675F4247016C765F4C560165745F4545016C745F4C5401756B5F5541010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003033BC4
-			echo -ne "Set language dataset - 0x280 - en_GB\n" | $TEE -a $LOG
-			DATASET_280=656E5F474200656E5F474200656E5F4742004331E45D
-		elif [[ "$TRAINVERSION" = *ER_AU276* ]] || [[ "$TRAINVERSION" = *ER_AU43x* ]] || [[ "$TRAINVERSION" = *ER_AU37x* ]] || [[ "$TRAINVERSION" = *MHI2Q_ER_AUG22* ]] || [[ "$TRAINVERSION" = *ER_AU62x* ]]; then
-			echo -ne "Set visible_MMI_language_dataset - 0x2d00 - EU\n" | $TEE -a $LOG
-			echo -ne "de_DE,en_GB,en_SA,fr_FR,it_IT,es_ES,pt_PT,pt_BR,nl_NL,ru_RU,pl_PL,cs_CZ,es_MX,en_US,sv_SE,tr_TR,hu_HU,no_NO,ar_SA,da_DK,ms_MY,ro_RO,sl_SI,fi_FI,el_GR,uk_UA\n"
-			DATASET_2D00=1A64655F444503656E5F474203656E5F53410266725F46520169745F49540165735F45530170745F50540170745F4252016E6C5F4E4C0172755F525501706C5F504C0163735F435A0165735F4D5801656E5F55530173765F53450174725F54520268755F4855016E6F5F4E4F0161725F53410164615F444B016D735F4D5900726F5F524F01736C5F53490166695F464901656C5F475201756B5F5541010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003033DAE5
-			echo -ne "Set language dataset - 0x280 - en_GB\n" | $TEE -a $LOG
-			DATASET_280=656E5F474200656E5F474200656E5F4742004331E45D
-		elif [[ "$TRAINVERSION" = *ER_AUG22* ]]; then
-			echo -ne "Set visible_MMI_language_dataset - 0x2d00 - EU\n" | $TEE -a $LOG
-			echo -ne "de_DE,en_GB,en_SA,fr_FR,it_IT,es_ES,pt_PT,pt_BR,nl_NL,ru_RU,pl_PL,cs_CZ,es_MX,en_US,sv_SE,tr_TR,hu_HU,no_NO,ar_SA\n"
-			DATASET_2D00=1364655F444503656E5F474203656E5F53410266725F46520169745F49540165735F45530170745F50540170745F4252016E6C5F4E4C0172755F525501706C5F504C0163735F435A0165735F4D5801656E5F55530173765F53450174725F54520268755F4855016E6F5F4E4F0161725F5341010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003033AB9A
-			echo -ne "Set language dataset - 0x280 - en_GB\n" | $TEE -a $LOG
-			DATASET_280=656E5F474200656E5F474200656E5F4742004331E45D
-		elif [[ "$TRAINVERSION" = *ER_AU57x* ]]; then
-			echo -ne "visible_MMI_language_dataset - 0x2d00 - EU\n" | $TEE -a $LOG
-			echo -ne "de_DE,en_GB,en_SA,fr_FR,it_IT,es_ES,pt_PT,pt_BR,nl_NL,ru_RU,pl_PL,cs_CZ,es_MX,en_US,sv_SE,tr_TR,ar_SA,en_SA\n"
-			DATASET_2D00=1264655F444503656E5F474203656E5F53410266725F46520169745F49540165735F45530170745F50540170745F4252016E6C5F4E4C0172755F525501706C5F504C0163735F435A0165735F4D5801656E5F55530173765F53450174725F54520261725F534101656E5F5341020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003033BA10
-			echo -ne "language dataset - 0x280 - en_GB\n" | $TEE -a $LOG
-			DATASET_280=656E5F474200656E5F474200656E5F4742004331E45D
-		else
-			echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
-			exit 1
-		fi
+		case $TRAINVERSION in
+			MHI2_ER_AUG22*)
+				echo -ne "Writing EU dataset 0x2D00 (visible_MMI_language_dataset):\n" | $TEE -a $LOG
+				echo -ne "de_DE,en_GB,en_SA,fr_FR,it_IT,es_ES,pt_PT,pt_BR,nl_NL,ru_RU,pl_PL,\n" | $TEE -a $LOG
+				echo -ne "cs_CZ,es_MX,en_US,sv_SE,tr_TR,hu_HU,no_NO,ar_SA\n" | $TEE -a $LOG
+				DATASET_2D00=1364655F444503656E5F474203656E5F53410266725F46520169745F49540165735F45530170745F50540170745F4252016E6C5F4E4C0172755F525501706C5F504C0163735F435A0165735F4D5801656E5F55530173765F53450174725F54520268755F4855016E6F5F4E4F0161725F5341010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003033AB9A
+				;;
+			*ER_AU276*|*ER_AU37x*|*ER_AU43x*|*ER_AU62x*|MHI2Q_ER_AUG22*)
+				echo -ne "Writing EU dataset 0x2D00 (visible_MMI_language_dataset):\n" | $TEE -a $LOG
+				echo -ne "de_DE,en_GB,en_SA,fr_FR,it_IT,es_ES,pt_PT,pt_BR,nl_NL,ru_RU,pl_PL,\n" | $TEE -a $LOG
+				echo -ne "cs_CZ,es_MX,en_US,sv_SE,tr_TR,hu_HU,no_NO,ar_SA,da_DK,ms_MY,ro_RO,\n" | $TEE -a $LOG
+				echo -ne "sl_SI,fi_FI,el_GR,uk_UA\n" | $TEE -a $LOG
+				DATASET_2D00=1A64655F444503656E5F474203656E5F53410266725F46520169745F49540165735F45530170745F50540170745F4252016E6C5F4E4C0172755F525501706C5F504C0163735F435A0165735F4D5801656E5F55530173765F53450174725F54520268755F4855016E6F5F4E4F0161725F53410164615F444B016D735F4D5900726F5F524F01736C5F53490166695F464901656C5F475201756B5F5541010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003033DAE5
+				;;
+			*ER_AU57x*)
+				echo -ne "Writing EU dataset 0x2D00 (visible_MMI_language_dataset):\n" | $TEE -a $LOG
+				echo -ne "de_DE,en_GB,en_SA,fr_FR,it_IT,es_ES,pt_PT,pt_BR,nl_NL,ru_RU,pl_PL,\n" | $TEE -a $LOG
+				echo -ne "cs_CZ,es_MX,en_US,sv_SE,tr_TR,ar_SA,en_SA\n"
+				DATASET_2D00=1264655F444503656E5F474203656E5F53410266725F46520169745F49540165735F45530170745F50540170745F4252016E6C5F4E4C0172755F525501706C5F504C0163735F435A0165735F4D5801656E5F55530173765F53450174725F54520261725F534101656E5F5341020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003033BA10
+				;;
+			*ER_BYSUV*|*ER_POG*)
+				echo -ne "Writing EU dataset 0x2D00 (visible_MMI_language_dataset):\n" | $TEE -a $LOG
+				echo -ne "de_DE,en_GB,en_SA,fr_FR,it_IT,es_ES,pt_PT,pt_BR,nl_NL,ru_RU,pl_PL,\n" | $TEE -a $LOG
+				echo -ne "cs_CZ,es_MX,en_US,sv_SE,tr_TR,hu_HU,no_NO,ar_SA,el_GR,fi_FI,hr_HR,\n" | $TEE -a $LOG
+				echo -ne "da_DK,sl_SI,sk_SK,sr_RS,ro_RO,bs_BA\n" | $TEE -a $LOG
+				DATASET_2D00=2064655F444503656E5F47420366725F46520169745F49540165735F4553016E6C5F4E4C0163735F435A0170745F50540173765F53450174725F54520272755F525501706C5F504C016E6F5F4E4F01656E5F55530165735F4D580170745F42520161725F53410162735F424101726F5F524F01736B5F534B01736C5F53490173725F52530164615F444B01656C5F47520168725F48520168755F48550166695F46490162675F4247016C765F4C560165745F4545016C745F4C5401756B5F5541010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003033BC4
+				;;
+			*ER_SEG*|*ER_SKG*|*ER_VWG*)
+				echo -ne "Writing EU dataset 0x2D00 (visible_MMI_language_dataset):\n" | $TEE -a $LOG
+				echo -ne "de_DE,en_GB,fr_FR,it_IT,es_ES,nl_NL,cs_CZ,pt_PT,sv_SE,tr_TR,ru_RU,\n" | $TEE -a $LOG
+				echo -ne "pl_PL,no_NO,en_US,es_MX,pt_BR,ar_SA,bs_BA,ro_RO,sk_SK,sl_SI,sr_RS,\n" | $TEE -a $LOG
+				echo -ne "da_DK,el_GR, hr_HR,hu_HU,fi_FI,bg_BG,lv_LV,et_EE,lt_LT,uk_UA\n" | $TEE -a $LOG
+				DATASET_2D00=2064655F444503656E5F47420366725F46520169745F49540165735F4553016E6C5F4E4C0163735F435A0170745F50540173765F53450174725F54520272755F525501706C5F504C016E6F5F4E4F01656E5F55530165735F4D580170745F42520161725F53410162735F424101726F5F524F01736B5F534B01736C5F53490173725F52530164615F444B01656C5F47520168725F48520168755F48550166695F46490162675F4247016C765F4C560165745F4545016C745F4C5401756B5F554101656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F47420163735F435A01656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F47420172755F52550130336D01
+				;;
+			*)
+				echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
+				exit 1 ;;
+		esac
+		echo -ne "Writing en_GB dataset 0x280 (language dataset)\n" | $TEE -a $LOG
+		DATASET_280=656E5F474200656E5F474200656E5F4742004331E45D
 	};;
 
 	-ar) {
