Code cleaning

diff --git a/apps/setlang b/apps/setlang
--- a/apps/setlang
+++ b/apps/setlang
@@ -68,16 +68,6 @@ case $1 in
 			echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
 			exit 1
 		fi
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			echo -ne "store changes to persistence\n" | $TEE -a $LOG
-			on -f mmx $PC b:0:1 0
-		#else
-		#	on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P 0 1 0
-		fi
-		echo -ne "All done!\n" | $TEE -a $LOG
-
-		trap 2
-		return 2> /dev/null
 	};;
 
 	-ar) {
@@ -86,21 +76,12 @@ case $1 in
 			echo -ne "visible_MMI_language_dataset - 0x2d00 - Arabic only\n" | $TEE -a $LOG
 			echo -ne "en_GB,ar_SA"
 			on -f mmx $PC b:10:0xC0030006 02656E5F47420261725F5341020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003332C898
-			sleep 1
 			echo -ne "language dataset - 0x280 - ar_SA\n" | $TEE -a $LOG
 			on -f mmx $PC b:10:0xC0030005 61725F53410161725F53410161725F5341014431A8FF
-			sleep 1
-			echo -ne "Language changed. DONE!\n" | $TEE -a $LOG
-			sleep 1		
 		else
-			echo -ne "no EU train found - will stop here\n" | $TEE -a $LOG
+			echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
+			exit 1
 		fi
-		#echo -ne "store changes to persistence\n"
-		on -f mmx $PC b:0:1 0
-		[ -z "$noboot" ] && echo -ne "All done!\n"
-
-		trap 2
-		return 2> /dev/null
 	};;
 
 	-nar) {
@@ -109,22 +90,12 @@ case $1 in
 			echo -ne "visible_MMI_language_dataset - 0x2d00 - NAR\n" | $TEE -a $LOG
 			echo -ne "en_US,es_MX,fr_CA"
 			on -f mmx $PC b:10:0xC0030006 03656E5F55530166725F43410165735F4D58010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003431E3E4
-			sleep 1
 			echo -ne "language dataset - 0x280 - en_US\n" | $TEE -a $LOG
 			on -f mmx $PC b:10:0xC0030005 656e5f555300656e5f555300656e5f5553004530c9a6
-			sleep 1
-			echo -ne "Language changed. DONE!\n" | $TEE -a $LOG
-			sleep 1		
 		else
-			echo -ne "no US train found - will stop here\n" | $TEE -a $LOG
+			echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
+			exit 1
 		fi
-
-		#echo -ne "store changes to persistence\n"
-		on -f mmx $PC b:0:1 0
-		[ -z "$noboot" ] && echo -ne "All done!\n"
-
-		trap 2
-		return 2> /dev/null
 	};;
 	
 	-jp) {
@@ -133,22 +104,12 @@ case $1 in
 			echo -ne "visible_MMI_language_dataset - 0x2d00 - Japan\n" | $TEE -a $LOG
 			echo -ne "ja_JP,en_US"
 			on -f mmx $PC b:10:0xC0030006 02656e5f5553016a615f4a5001656e5f555301656e5f555301000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000363090a9
-			sleep 1
 			echo -ne "language dataset - 0x280 - ja_JP\n" | $TEE -a $LOG
 			on -f mmx $PC b:10:0xC0030005 6a615f4a50006a615f4a50006a615f4a500033335be3
-			sleep 1
-			echo -ne "Language changed. DONE!\n" | $TEE -a $LOG
-			sleep 1		
 		else
-			echo -ne "no JP train found - will stop here\n" | $TEE -a $LOG
+			echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
+			exit 1
 		fi
-
-		#echo -ne "store changes to persistence\n"
-		on -f mmx $PC b:0:1 0
-		[ -z "$noboot" ] && echo -ne "All done!\n"
-
-		trap 2
-		return 2> /dev/null
 	};;
 
 	-kr) {
@@ -157,22 +118,12 @@ case $1 in
 			echo -ne "visible_MMI_language_dataset - 0x2d00 - Korea\n" | $TEE -a $LOG
 			echo -ne "ko_KR,en_KR"
 			on -f mmx $PC b:10:0xC0030006 026b6f5f4b5201656e5f4b52010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003731cc83
-			sleep 1
 			echo -ne "language dataset - 0x280 - ko_KR\n" | $TEE -a $LOG
 			on -f mmx $PC b:10:0xC0030005 6b6f5f4b52006b6f5f4b52006b6f5f4b52004c30a910
-			sleep 1
-			echo -ne "Language changed. DONE!\n" | $TEE -a $LOG
-			sleep 1		
 		else
-			echo -ne "no KR train found - will stop here\n" | $TEE -a $LOG
+			echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
+			exit 1
 		fi
-
-		#echo -ne "store changes to persistence\n"
-		on -f mmx $PC b:0:1 0
-		[ -z "$noboot" ] && echo -ne "All done!\n"
-
-		trap 2
-		return 2> /dev/null
 	};;
 	
 	-tw) {
@@ -181,22 +132,12 @@ case $1 in
 			echo -ne "visible_MMI_language_dataset - 0x2d00 - Taiwan\n" | $TEE -a $LOG
 			echo -ne "zh_TW,en_US"
 			on -f mmx $PC b:10:0xC0030006 027a685f545701656e5f5457010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003831ba2c
-			sleep 1
 			echo -ne "language dataset - 0x280 - zh_TW\n" | $TEE -a $LOG
 			on -f mmx $PC b:10:0xC0030005 7a685f5457007a685f5457007a685f5457004a307125
-			sleep 1
-			echo -ne "Language changed. DONE!\n" | $TEE -a $LOG
-			sleep 1		
 		else
-			echo -ne "no TW train found - will stop here\n" | $TEE -a $LOG
+			echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
+			exit 1
 		fi
-
-		#echo -ne "store changes to persistence\n"
-		on -f mmx $PC b:0:1 0
-		[ -z "$noboot" ] && echo -ne "All done!\n"
-
-		trap 2
-		return 2> /dev/null
 	};;
 
 	-cn) {
@@ -205,22 +146,13 @@ case $1 in
 			echo -ne "visible_MMI_language_dataset - 0x2d00 - China\n" | $TEE -a $LOG
 			echo -ne "zh_CN,zh_HK,en_CN"
 			on -f mmx $PC b:10:0xC0030006 037a685f434e017a685f484b01656e5f434e0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035318ba2
-			sleep 1
 			echo -ne "language dataset - 0x280 - zh_CN\n" | $TEE -a $LOG
 			on -f mmx $PC b:10:0xC0030005 7a685f434e007a685f434e007a685f434e004830a705
-			sleep 1
 			echo -ne "Language changed. DONE!\n" | $TEE -a $LOG
-			sleep 1		
 		else
-			echo -ne "no CN train found - will stop here\n" | $TEE -a $LOG
+			echo -ne "Aborted. No supported train found!\n" | $TEE -a $LOG
+			exit 1
 		fi
-
-		#echo -ne "store changes to persistence\n"
-		on -f mmx $PC b:0:1 0
-		[ -z "$noboot" ] && echo -ne "All done!\n"
-
-		trap 2
-		return 2> /dev/null
 	};;
 
 # help or unknown parameter ------------------------------
@@ -258,4 +190,14 @@ case $1 in
 		echo ""
 	};;
 esac
-exit 0
+
+if [[ ! -z "$1" ]] && [[ "$1" != "--help" ]]; then 
+	if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+		echo -ne "Storing changes to persistence...\n" | $TEE -a $LOG
+		on -f mmx $PC b:0:1 0
+	fi
+	echo -ne "All done!\n" | $TEE -a $LOG
+fi
+
+trap 2
+return 2> /dev/null
