Logic and typo fixes

diff --git a/apps/setreg b/apps/setreg
--- a/apps/setreg
+++ b/apps/setreg
@@ -16,7 +16,7 @@ fi
 echo -ne "\n$ME-$thisname---->\n" | $TEE -i -a $LOG
 
 if [ -f $TMP/reboot.mib ]; then
-	echo "Reboot running..."
+	echo -ne "Aborted because the reboot is running...\n" | $TEE -a $LOG
 	return 2> /dev/null
 fi
 
@@ -31,170 +31,169 @@ TRAINVERSION="$(on -f rcc /net/rcc/usr/apps/modifyE2P r 3A0 13 | $SED -rn 's/^0x
 
 case $1 in
 	-eu) {
-	trap '' 2
-	mount -uw /net/rcc/mnt/efs-persist
-	if [[ "$TRAINVERSION" = *ER* ]]; then
-		echo -ne "Writing EU language datasets to 5F...\n" | $TEE -a $LOG
-		. /net/mmx/fs/sda0/apps/setlang -eu -noboot
-		echo -ne "\nChanging coding and adaptations to EU:"
-		echo -ne "\n--- Summertime algo.\n" | $TEE -a $LOG
-		# 0=none, 1=manual, 2=MESZ, 3=USA
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:28442848:503 2
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 503 2
-		fi
-		
-		echo -ne "--- FM Bandsetting\n" | $TEE -a $LOG
-		# 0=BAND_FM_NO_SETTING, 1=BAND_FM_EU_RDW, 2=BAND_FM_NAR, 3=BAND_FM_JP, 4=BAND_FM_KOR
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:0:0x5018240F 1
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343759375 1
-		fi
-		
-		echo -ne "--- AM Bandsetting\n" | $TEE -a $LOG
-		# 0=BAND_AM_NO_SETTING, 1=BAND_AM_EU_RDW, 2=BAND_AM_NAR, 3=BAND_AM_JP, 4=BAND_AM_EU, 5=BAND_AM_AUS
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:0:0x501824F0 1
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343759600 1
-		fi
-		
-		#echo -ne "--- DAB Bandsetting 1\n"
-		# 0=BAND_DAB1_OFF, 1=BAND_DAB1_EU_BAND_III-N, 2=BAND_DAB1_EU_BAND_III (EU default), 3=BAND_DAB1_CANADA_L_BAND
-		# 4=BAND_DAB1_KOREA_BAND_III, 5=BAND_DAB1_CHINA_BAND_III, 6=BAND_DAB1_DOWNLOAD_TABLE_1, 7=BAND_DAB1_NEW_ZEALAND_BAND_III
-		#on -f mmx $PC i:0:0x5018280F 0
+		trap '' 2
+		mount -uw /net/rcc/mnt/efs-persist
+		if [[ "$TRAINVERSION" = *ER* ]]; then
+			echo -ne "Writing EU language datasets to 5F...\n" | $TEE -a $LOG
+			. /net/mmx/fs/sda0/apps/setlang -eu
+			echo -ne "\nChanging coding and adaptations to EU:"
+			echo -ne "\n--- Summertime algo.\n" | $TEE -a $LOG
+			# 0=none, 1=manual, 2=MESZ, 3=USA
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:28442848:503 2
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 503 2
+			fi
+			
+			echo -ne "--- FM Bandsetting\n" | $TEE -a $LOG
+			# 0=BAND_FM_NO_SETTING, 1=BAND_FM_EU_RDW, 2=BAND_FM_NAR, 3=BAND_FM_JP, 4=BAND_FM_KOR
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:0:0x5018240F 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343759375 1
+			fi
+			
+			echo -ne "--- AM Bandsetting\n" | $TEE -a $LOG
+			# 0=BAND_AM_NO_SETTING, 1=BAND_AM_EU_RDW, 2=BAND_AM_NAR, 3=BAND_AM_JP, 4=BAND_AM_EU, 5=BAND_AM_AUS
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:0:0x501824F0 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343759600 1
+			fi
+			
+			#echo -ne "--- DAB Bandsetting 1\n"
+			# 0=BAND_DAB1_OFF, 1=BAND_DAB1_EU_BAND_III-N, 2=BAND_DAB1_EU_BAND_III (EU default), 3=BAND_DAB1_CANADA_L_BAND
+			# 4=BAND_DAB1_KOREA_BAND_III, 5=BAND_DAB1_CHINA_BAND_III, 6=BAND_DAB1_DOWNLOAD_TABLE_1, 7=BAND_DAB1_NEW_ZEALAND_BAND_III
+			#on -f mmx $PC i:0:0x5018280F 0
 
-		#echo -ne "--- DAB Bandsetting 2\n"
-		# 0=BAND_DAB2_OFF, 1=BAND_DAB2_L_BAND (EU default), 2=BAND_DAB2_DOWNLOAD_TABLE_2
-		#on -f mmx $PC i:0:0x501828F0 0
+			#echo -ne "--- DAB Bandsetting 2\n"
+			# 0=BAND_DAB2_OFF, 1=BAND_DAB2_L_BAND (EU default), 2=BAND_DAB2_DOWNLOAD_TABLE_2
+			#on -f mmx $PC i:0:0x501828F0 0
 
-		echo -ne "--- Radiotext+ off/on\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:0:0x50183408 1
+			echo -ne "--- Radiotext+ off/on\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:0:0x50183408 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343763464 1
+			fi
+
+			echo -ne "--- Navigation Country\n" | $TEE -a $LOG
+			# 1=EU, 2=NAR, 3=MSA, 4=Korea, 5=China, 6=Japan, 7=AsiaPacific, 8=Australia, 9=South Africa, 10=NEAST,
+			# 11=NMAfrica, 12=MEAST, 13=CentralAsia, 14=India, 15=Israel, 16=Taiwan, 17=MSA 2 (Chile)
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:0:0x50180CFF 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343753471 1
+			fi
+
+			echo -ne "--- Import media\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:0:0x50186010 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343774736 1
+			fi
+
+			echo -ne "--- Media Ripping\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:0:0x50186020 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343774752 1
+			fi
+
+			echo -ne "--- Regional Codes DVD\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:28442848:515 2
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 515 2
+			fi
+
+			echo -ne "--- Regional Codes Blueray\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:28442848:516 2
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 516 2
+			fi
+
+			echo -ne "--- Regional Codes DVD Counter\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:28442848:517 5
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 517 5
+			fi
+
+			echo -ne "--- Regional Codes Blueray Counter\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:28442848:518 5
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 518 5
+			fi
+			
+			echo -ne "--- TMCPro EU\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:28442848:520 32783
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 520 32783
+			fi
+
+			echo -ne "--- Gracenote local ON\n" | $TEE -a $LOG
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC b:0:3221356628:1.6 1
+				on -f mmx $PC b:0:3221356628:1.7 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P -L 1 -O 9 0 3221356628 F
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P -L 1 -O 8 0 3221356628 F
+			fi
+
+			echo -ne "--- Radio stationlogo DB\n" | $TEE -a $LOG
+			#	0=none, 1=EU, 28=China, 66=Hongkong, Macao=67, CD=Korea, EA=Taiwan
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC b:0:3221356628:6 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P -L 8 -O 48 0 3221356628 01
+			fi
+			
+			echo -ne "--- SDS region Flag\n" | $TEE -a $LOG
+			# 0=no region, 1=EU, 2=NAR, 3=MSA, 4=Korea, 5=China, 6=Japan, 7=AsiaPacific, 8=Australia, 9=South Africa, 10=NEAST,
+			# 11=NMAfrica, 12=MEAST, 13=CentralAsia, 14=India, 15=Israel, 16=Taiwan, 17=MSA 2 (Chile), 18=China 2, 19=China 3
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC b:0:3221356628:9 1
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P -L 8 -O 54 0 3221356628 01
+			fi
+
+			echo -ne "--- Variant region\n" | $TEE -a $LOG
+			# 1=Europe/ROW, 2=Europe, 3=NAR, 4=ROW, 5=China, 6=Japan, 7=Korea, 8=Asia, 9=Taiwan
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:0x286f058c:9 2
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 678364556 9 2
+			fi
+
+			#echo -ne "switch variant feature byte type to High\n"
+			#on -f mmx $PC i:0x286f058c:4 1
+
+			echo -ne "--- Disable variant feature byte sirius\n"
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				on -f mmx $PC i:0x286f058c:8 0
+			else
+				on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 678364556 8 0
+			fi
+
+			if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
+				echo -ne "--- Store changes to persistence\n\n"
+				on -f mmx $PC b:0:1 0
+			#else
+			#	on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P 0 1 0
+			fi
+
+			[ -z "$noboot" ] && echo -ne "\nAll done!\n"
 		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343763464 1
+			echo -ne "Skipped as unit has non EU train.\n" | $TEE -a $LOG
+			exit 1
 		fi
 
-		echo -ne "--- Navigation Country\n" | $TEE -a $LOG
-		# 1=EU, 2=NAR, 3=MSA, 4=Korea, 5=China, 6=Japan, 7=AsiaPacific, 8=Australia, 9=South Africa, 10=NEAST,
-		# 11=NMAfrica, 12=MEAST, 13=CentralAsia, 14=India, 15=Israel, 16=Taiwan, 17=MSA 2 (Chile)
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:0:0x50180CFF 1
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343753471 1
-		fi
-
-		echo -ne "--- Import media\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:0:0x50186010 1
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343774736 1
-		fi
-
-		echo -ne "--- Media Ripping\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:0:0x50186020 1
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 0 1343774752 1
-		fi
-
-		echo -ne "--- Regional Codes DVD\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:28442848:515 2
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 515 2
-		fi
-
-		echo -ne "--- Regional Codes Blueray\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:28442848:516 2
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 516 2
-		fi
-
-		echo -ne "--- Regional Codes DVD Counter\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:28442848:517 5
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 517 5
-		fi
-
-		echo -ne "--- Regional Codes Blueray Counter\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:28442848:518 5
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 518 5
-		fi
-		
-		echo -ne "--- TMCPro EU\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:28442848:520 32783
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 28442848 520 32783
-		fi
-
-		echo -ne "--- Gracenote local ON\n" | $TEE -a $LOG
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC b:0:3221356628:1.6 1
-			on -f mmx $PC b:0:3221356628:1.7 1
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P -L 1 -O 9 0 3221356628 F
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P -L 1 -O 8 0 3221356628 F
-		fi
-
-		echo -ne "--- Radio stationlogo DB\n" | $TEE -a $LOG
-		#	0=none, 1=EU, 28=China, 66=Hongkong, Macao=67, CD=Korea, EA=Taiwan
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC b:0:3221356628:6 1
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P -L 8 -O 48 0 3221356628 01
-		fi
-		
-		echo -ne "--- SDS region Flag\n" | $TEE -a $LOG
-		# 0=no region, 1=EU, 2=NAR, 3=MSA, 4=Korea, 5=China, 6=Japan, 7=AsiaPacific, 8=Australia, 9=South Africa, 10=NEAST,
-		# 11=NMAfrica, 12=MEAST, 13=CentralAsia, 14=India, 15=Israel, 16=Taiwan, 17=MSA 2 (Chile), 18=China 2, 19=China 3
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC b:0:3221356628:9 1
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P -L 8 -O 54 0 3221356628 01
-		fi
-
-		echo -ne "--- Variant region\n" | $TEE -a $LOG
-		# 1=Europe/ROW, 2=Europe, 3=NAR, 4=ROW, 5=China, 6=Japan, 7=Korea, 8=Asia, 9=Taiwan
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:0x286f058c:9 2
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 678364556 9 2
-		fi
-
-		#echo -ne "switch variant feature byte type to High\n"
-		#on -f mmx $PC i:0x286f058c:4 1
-
-		echo -ne "--- Disable variant feature byte sirius\n"
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			on -f mmx $PC i:0x286f058c:8 0
-		else
-			on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -t int 678364556 8 0
-		fi
-
-		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then
-			echo -ne "--- Store changes to persistence\n\n"
-			on -f mmx $PC b:0:1 0
-		#else
-		#	on -f mmx /net/mmx/eso/bin/dumb_persistence_writer -P 0 1 0
-		fi
-
-		[ -z "$noboot" ] && echo -ne "\nAll done!\n"
-	else
-		echo -ne "Skipped as unit has non EU train.\n" | $TEE -a $LOG
-		exit 1
-	fi
-
-	# return 2> /dev/null
-	trap 2
-	[ -z "$noboot" ] && . $thisdir/reboot -t 10
+		trap 2
+		[ -z "$noboot" ] && . $thisdir/reboot -t 10
 	};;
 
 	# help or unknown parameter ------------------------------
@@ -205,8 +204,8 @@ case $1 in
 		echo "Usage: "$thisname" [OPTION] [-noboot]"
 		echo ""
 		echo "Options:"
-		echo "        -eu			set Region to EU"
-		echo "        --help		show this help"
+		echo "        -eu           set Region to EU"
+		echo "        --help        show this help"
 		echo ""
 		echo "Note: Backup will only work in RCC bash!"
 		echo ""
@@ -224,9 +223,6 @@ case $1 in
 		echo "along with this program; if not, write to the Free Software Foundation,"
 		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
 		echo ""
-
 	};;
-
-	esac
-
+esac
 exit 0
diff --git a/apps/setvariant b/apps/setvariant
--- a/apps/setvariant
+++ b/apps/setvariant
@@ -16,7 +16,7 @@ fi
 echo -ne "\n$ME-$thisname---->\n" | $TEE -i -a $LOG
 
 if [ -f $TMP/reboot.mib ]; then
-	echo "Reboot running..."
+	echo -ne "Aborted because the reboot is running...\n" | $TEE -a $LOG
 	return 2> /dev/null
 fi
 
@@ -26,152 +26,146 @@ else
 	noboot=""
 fi
 
-	case $1 in
-
+case $1 in
 	-var) {
+		trap '' 2
+		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then #non legacy mode
+			VARIANT2="$(on -f mmx $PC s:678364556:12 2> /dev/null | $SED 's/[^a-zA-Z0-9_-]//g')"
+		else
+			VARIANT2="$($SED -n 's/Variant = '\''\(.*\)'\''/\1/p' /net/rcc/dev/shmem/version.txt | $SED 's/[^a-zA-Z0-9._-]//g')"
+			VARTYPE="$(echo "$VARIANT2" | awk -F '-' '{print $2}' 2>/dev/null)"
+			VARLTE="$(echo "$VARIANT2" | awk -F '-' '{print $3}' 2>/dev/null)"
+			#TNDL in Variant_2 is LND in Variant_1, TNL>LN
+			VARLTE="$(echo "$VARLTE" | $SED 's/TNDL/LND/')"
+			VARLTE="$(echo "$VARLTE" | $SED 's/TNL/LN/')"
+			VARNAV=""
+			VARDAB=""
+			VARSIR=""
+			VARREG="45 55 " #EU
+		fi
+		echo -ne "Variant_2: $VARIANT2\n"
+		COMPONENT="$(on -f rcc /net/rcc/usr/apps/modifyE2P r BA D | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )"
+		echo -ne "Сurrent Variant_1: $COMPONENT\n" | $TEE -i -a $LOG
 
-trap '' 2
+		VARERROR=0
+		if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then #non legacy mode
+			echo -ne "Reading persistence...\n" | $TEE -i -a $LOG
+			#Type
+			VARTYPE="$(on -f mmx $PC i:0x286f058c:4)"
+			#Telephone 0/1
+			#VARTEL="$(on -f mmx $PC i:0x286f058c:5)"
+			#Navigation EU
+			VARNAV="$(on -f mmx $PC i:0x286f058c:6)"
+			#DAB 0/1
+			VARDAB="$(on -f mmx $PC i:0x286f058c:7)"
+			#sirius 0/1
+			VARSIR="$(on -f mmx $PC i:0x286f058c:8)"
+			# LTE 0/1
+			VARLTE="$(on -f mmx $PC i:0x286f058c:17)"
+			# region EU
+			VARREG="$(on -f mmx $PC i:0x286f058c:9)"
+			#error handler for variant_1
 
-if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then #non legacy mode
-	VARIANT2="$(on -f mmx $PC s:678364556:12 2> /dev/null | $SED 's/[^a-zA-Z0-9_-]//g')"
-else
-	VARIANT2="$($SED -n 's/Variant = '\''\(.*\)'\''/\1/p' /net/rcc/dev/shmem/version.txt | $SED 's/[^a-zA-Z0-9._-]//g')"
-	VARTYPE="$(echo "$VARIANT2" | awk -F '-' '{print $2}' 2>/dev/null)"
-	VARLTE="$(echo "$VARIANT2" | awk -F '-' '{print $3}' 2>/dev/null)"
-	#TNDL in Variant_2 is LND in Variant_1, TNL>LN
-	VARLTE="$(echo "$VARLTE" | $SED 's/TNDL/LND/')"
-	VARLTE="$(echo "$VARLTE" | $SED 's/TNL/LN/')"
-	VARNAV=""
-	VARDAB=""
-	VARSIR=""
-	VARREG="45 55 " #EU
-fi
-echo -ne "Variant_2: $VARIANT2\n"
-COMPONENT="$(on -f rcc /net/rcc/usr/apps/modifyE2P r BA D | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )"
-echo -ne "Сurrent Variant_1: $COMPONENT\n" | $TEE -i -a $LOG
+			if [ $VARTYPE = 1 ]; then #High
+				VARTYPE="48 "
+			elif [ $VARTYPE = 4 ]; then #Premium
+				VARTYPE="50 "
+			else
+				echo -ne "Type unknown\n" | $TEE -i -a $LOG
+				VARTYPE=""
+				VARERROR=1
+			fi
 
-VARERROR=0
-if [ -f /net/mmx/mnt/app/eso/bin/apps/pc ]; then #non legacy mode
-	echo -ne "Reading persistence...\n" | $TEE -i -a $LOG
-	#Type
-	VARTYPE="$(on -f mmx $PC i:0x286f058c:4)"
-	#Telephone 0/1
-	#VARTEL="$(on -f mmx $PC i:0x286f058c:5)"
-	#Navigation EU
-	VARNAV="$(on -f mmx $PC i:0x286f058c:6)"
-	#DAB 0/1
-	VARDAB="$(on -f mmx $PC i:0x286f058c:7)"
-	#sirius 0/1
-	VARSIR="$(on -f mmx $PC i:0x286f058c:8)"
-	# LTE 0/1
-	VARLTE="$(on -f mmx $PC i:0x286f058c:17)"
-	# region EU
-	VARREG="$(on -f mmx $PC i:0x286f058c:9)"
-	#error handler for variant_1
+			#if [ $VARTEL = 1 ]; then #ENABLED
+			#	VARTEL="54 "
+			#elif [ $VARTEL = 0 ]; then #OFF
+			#	VARTEL=""
+			#else
+			#	echo -ne "Telephone status unknown\n" | $TEE -i -a $LOG
+			#	VARTEL=""
+			#	VARERROR=1
+			#fi
 
-	if [ $VARTYPE = 1 ]; then #High
-		VARTYPE="48 "
-	elif [ $VARTYPE = 4 ]; then #Premium
-		VARTYPE="50 "
-	else
-		echo -ne "Type unknown\n" | $TEE -i -a $LOG
-		VARTYPE=""
-		VARERROR=1
-	fi
+			if [ $VARNAV = 1 ]; then #ENABLED
+				VARNAV="4e "
+			elif [ $VARNAV = 0 ]; then #OFF
+				VARNAV=""
+			else
+				echo -ne "Navigation status unknown\n" | $TEE -i -a $LOG
+				VARNAV=""
+				VARERROR=1
+			fi
 
-	#if [ $VARTEL = 1 ]; then #ENABLED
-	#	VARTEL="54 "
-	#elif [ $VARTEL = 0 ]; then #OFF
-	#	VARTEL=""
-	#else
-	#	echo -ne "Telephone status unknown\n" | $TEE -i -a $LOG
-	#	VARTEL=""
-	#	VARERROR=1
-	#fi
+			if [ $VARDAB = 1 ]; then #ENABLED
+				VARDAB="44 "
+			elif [ $VARDAB = 0 ]; then #OFF
+				VARDAB=""
+			else
+				echo -ne "DAB status unknown\n" | $TEE -i -a $LOG
+				VARDAB=""
+				VARERROR=1
+			fi
 
-	if [ $VARNAV = 1 ]; then #ENABLED
-		VARNAV="4e "
-	elif [ $VARNAV = 0 ]; then #OFF
-		VARNAV=""
-	else
-		echo -ne "Navigation status unknown\n" | $TEE -i -a $LOG
-		VARNAV=""
-		VARERROR=1
-	fi
+			if [ $VARSIR = 1 ]; then #ENABLED
+				VARSIR="53 "
+			elif [ $VARSIR = 0 ]; then #OFF
+				VARSIR=""
+			else
+				echo -ne "Sirius status unknown\n" | $TEE -i -a $LOG
+				VARSIR=""
+				VARERROR=1
+			fi
 
-	if [ $VARDAB = 1 ]; then #ENABLED
-		VARDAB="44 "
-	elif [ $VARDAB = 0 ]; then #OFF
-		VARDAB=""
-	else
-		echo -ne "DAB status unknown\n" | $TEE -i -a $LOG
-		VARDAB=""
-		VARERROR=1
-	fi
+			if [ $VARLTE = 1 ]; then #ENABLED
+				VARLTE="4c "
+			elif [ $VARLTE = 0 ]; then #OFF
+				VARLTE=""
+			else
+				echo -ne "LTE status unknown\n" | $TEE -i -a $LOG
+				VARLTE=""
+				VARERROR=1
+			fi
 
-	if [ $VARSIR = 1 ]; then #ENABLED
-		VARSIR="53 "
-	elif [ $VARSIR = 0 ]; then #OFF
-		VARSIR=""
-	else
-		echo -ne "Sirius status unknown\n" | $TEE -i -a $LOG
-		VARSIR=""
-		VARERROR=1
-	fi
+			case $VARREG in
+				1) VARREG="45 52 " ;; #ER
+				2) VARREG="45 55 " ;; #EU
+				3) VARREG="55 53 " ;; #US
+				4) VARREG="52 57 " ;; #RW
+				5) VARREG="43 4e " ;; #CN
+				6) VARREG="4a 50 " ;; #JP
+				7) VARREG="4B 52 " ;; #KR
+				8) VARREG=""		  #Asia?
+					echo -ne "Region code 8 unknown\n" | $TEE -i -a $LOG
+					VARERROR=1 ;;
+				9) VARREG="54 57 " ;; #TW
+				*) VARREG=""
+					echo -ne "Region unknown\n" | $TEE -i -a $LOG
+					VARERROR=1 ;;
+			esac
+		fi
 
-	if [ $VARLTE = 1 ]; then #ENABLED
-		VARLTE="4c "
-	elif [ $VARLTE = 0 ]; then #OFF
-		VARLTE=""
-	else
-		echo -ne "LTE status unknown\n" | $TEE -i -a $LOG
-		VARLTE=""
-		VARERROR=1
-	fi
-
-	case $VARREG in
-		1) VARREG="45 52 " ;; #ER
-		2) VARREG="45 55 " ;; #EU
-		3) VARREG="55 53 " ;; #US
-		4) VARREG="52 57 " ;; #RW
-		5) VARREG="43 4e " ;; #CN
-		6) VARREG="4a 50 " ;; #JP
-		7) VARREG="4B 52 " ;; #KR
-		8) VARREG=""		  #Asia?
-			echo -ne "Region code 8 unknown\n" | $TEE -i -a $LOG
-			VARERROR=1 ;;
-		9) VARREG="54 57 " ;; #TW
-		*) VARREG=""
-			echo -ne "Region unknown\n" | $TEE -i -a $LOG
-			VARERROR=1 ;;
-	esac
-fi
-
-if [ $VARERROR = 0 ]; then
-	echo -ne "Cleaning Variant_1 in EEPROM(writing 13 zero bytes)\n" | $TEE -i -a $LOG
-	on -f rcc /usr/apps/modifyE2P w BA 00 00 00 00 00 00 00 00 00 00 00 00 00 >> $LOG
-	#Build Variant_1 string 
-	EVAR="4d 55 2d "$VARTYPE"2d "$VARLTE$VARNAV$VARDAB$VARSIR"2d "$VARREG
-	#EVAR=$(echo "$EVAR" | $SED -r 's/[[:space:]]//g')
-	#AVAR=$(on -f mmx $VOLUME/apps/hex2ascii -convert $EVAR)
-	AVAR=$(echo "$EVAR" | $XXD -r -p)
-	echo -ne "Variant_1 generated from Variant_2: "$AVAR"\n" | $TEE -i -a $LOG
-	echo -ne "Writing generated Variant_1 into EEPROM\n" | $TEE -i -a $LOG
-	on -f rcc /usr/apps/modifyE2P w BA $EVAR >> $LOG
-	COMPONENT="$(on -f rcc /net/rcc/usr/apps/modifyE2P r BA D | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )"
-	echo -ne "Variant_1 in EEPROM: $COMPONENT\n" | $TEE -i -a $LOG
-else
-	echo -ne "Aborted. Cannot generate Variant_1!\n" | $TEE -i -a $LOG
-	exit 1
-fi
-
-trap 2
-[ -z "$noboot" ] && echo -ne ""
-echo -ne "\nAll done! To apply changes unit will autoreboot in 10 seconds\n"
-[ -z "$noboot" ] && . $thisdir/reboot -t 10
-
-return 2> /dev/null
-
+		if [ $VARERROR = 0 ]; then
+			echo -ne "Cleaning Variant_1 in EEPROM(writing 13 zero bytes)\n" | $TEE -i -a $LOG
+			on -f rcc /usr/apps/modifyE2P w BA 00 00 00 00 00 00 00 00 00 00 00 00 00 >> $LOG
+			#Build Variant_1 string 
+			EVAR="4d 55 2d "$VARTYPE"2d "$VARLTE$VARNAV$VARDAB$VARSIR"2d "$VARREG
+			#EVAR=$(echo "$EVAR" | $SED -r 's/[[:space:]]//g')
+			#AVAR=$(on -f mmx $VOLUME/apps/hex2ascii -convert $EVAR)
+			AVAR=$(echo "$EVAR" | $XXD -r -p)
+			echo -ne "Variant_1 generated from Variant_2: "$AVAR"\n" | $TEE -i -a $LOG
+			echo -ne "Writing generated Variant_1 into EEPROM\n" | $TEE -i -a $LOG
+			on -f rcc /usr/apps/modifyE2P w BA $EVAR >> $LOG
+			COMPONENT="$(on -f rcc /net/rcc/usr/apps/modifyE2P r BA D | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )"
+			echo -ne "Variant_1 in EEPROM: $COMPONENT\n" | $TEE -i -a $LOG
+		else
+			echo -ne "Aborted. Cannot generate Variant_1!\n" | $TEE -i -a $LOG
+			exit 1
+		fi
+		
+		trap 2
+		echo -ne "\nAll done! Changes will become active after reboot of the unit.\n"
+		[ -z "$noboot" ] && . $thisdir/reboot -t 10
+		return 2> /dev/null
 	};;
 
 	# help or unknown parameter ------------------------------
@@ -182,8 +176,8 @@ return 2> /dev/null
 		echo "Usage: "$thisname" [OPTION] [-noboot]"
 		echo ""
 		echo "Options:"
-		echo "        -var			set variant_1"
-		echo "        --help			show this help"
+		echo "        -var          set variant_1"
+		echo "        --help        show this help"
 		echo ""
 		echo "Note: Backup will only work in RCC bash!"
 		echo ""
@@ -201,9 +195,6 @@ return 2> /dev/null
 		echo "along with this program; if not, write to the Free Software Foundation,"
 		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
 		echo ""
-
 	};;
-
-	esac
-
+esac
 exit 0
