removed LOG bug

diff --git a/apps/showimage b/apps/showimage
--- a/apps/showimage
+++ b/apps/showimage
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-revision="showimage v0.1.6 (2023-06-21 by Mib-Wiki)"
+revision="showimage v0.1.7 (2023-06-26 by Mib-Wiki)"
 # use --help for more info
 
 export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
@@ -21,108 +21,118 @@ MIBCAP=3
 DMDT="on -f mmx /net/mmx/eso/bin/apps/dmdt"
 DMRCClient="on -f mmx /net/mmx/eso/bin/apps/DMRCClient"
 
-	case $1 in
 
-	-load) {
+case $1 in
+
+-load) {
 # <duration in s> <path> <filename>
 # supported image formats: /
 # jpeg, png, gif (no animations), bmp
 
-trap '' 2
+if [ ! -z $1 ]; then
+	STOP=0
+	if [ -z $2 ]; then
+		echo -ne "--- DURATION in s missing\n    0 s will display the image on screen until -unload is used\n"
+		STOP=1
+	fi
+	if [ -z $3 ]; then
+		echo -ne "--- PATH to the image file missing\n"
+		STOP=1
+	fi
+	if [ -z $4 ]; then
+		echo -ne "--- Filename missing\n"
+		STOP=1
+	fi
+	if [ $STOP = 1 ]; then
+		echo -ne "test\n"
+		exit 0
+	fi
+fi
 
-if [[ "$TRAINVERSION" = *MHIG* ]]; then
-	LOADANDSHOWIMAGE="on -f mmx /net/mmx/eso/bin/apps/loadandshowimage"
-	export LIBIMG_CFGFILE=/net/mmx/etc/config/img.conf 2>> $LOG
-	#export LD_LIBRARY_PATH=/net/mmx/eso/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/app/armle/lib/dll 2>> $LOG
-	$LOADANDSHOWIMAGE ${3}${4}&
-	#export LD_LIBRARY_PATH=/net/mmx/eso/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/root/lib-target
-	#export IPL_CONFIG_DIR=/net/mmx/etc/eso/production 2>> $LOG
-	$DMRCClient -mv 99 2>> $LOG # trigger display of image
-	#export LD_LIBRARY_PATH=/net/mmx/eso/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/root/lib-target
-	#export IPL_CONFIG_DIR=/net/mmx/etc/eso/production
-	$DMRCClient -mv 99 2>> $LOG # trigger display of image
-	if [[ $2 = 0 ]]; then
-		echo -ne "No end time for image set\nStop image display with -unload\n" | $TEE -i -a $LOG
+	trap '' 2
+
+	if [[ "$TRAINVERSION" = *MHIG* ]]; then
+		LOADANDSHOWIMAGE="on -f mmx /net/mmx/eso/bin/apps/loadandshowimage"
+		export LIBIMG_CFGFILE=/net/mmx/etc/config/img.conf 2>> $LOG
+		$LOADANDSHOWIMAGE ${3}${4}&
+		$DMRCClient -mv 99 2>> $LOG # trigger display of image
+
+		$DMRCClient -mv 99 2>> $LOG # trigger display of image
+		if [[ $2 = 0 ]]; then
+			echo -ne "No end time for image set\nStop image display with -unload\n" | $TEE -i -a $LOG
+		else
+			sleep $2
+			$LOADANDSHOWIMAGE 1 2 3 4 5 #unload image
+			$DMRCClient -mv 2>> $LOG # switch back to standard output screen
+		fi
 	else
-		sleep $2
-		#export LD_LIBRARY_PATH=/net/mmx/eso/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/root/lib-target
-		$LOADANDSHOWIMAGE 1 2 3 4 5 #unload image
-		#export LD_LIBRARY_PATH=/net/mmx/eso/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/root/lib-target
-		#export IPL_CONFIG_DIR=/net/mmx/etc/eso/production
+		LOADANDSHOWIMAGE="/net/mmx/eso/bin/apps/loadandshowimage"
+		export LIBIMG_CFGFILE=/net/mmx/etc/imgprocessing.cfg
+		if [[ $5 = "SWDL" ]]; then
+			on -f mmx $LOADANDSHOWIMAGE ${3}${4}& >> $LOG
+		else
+			$LOADANDSHOWIMAGE ${3}${4}& >> $LOG
+		fi
+		$DMDT sc 0 -9 2>> $LOG # trigger display of image
+		if [[ $2 = 0 ]]; then
+			echo -ne "No end time for image set\n--- Stop image display with -unload\n" | $TEE -i -a $LOG
+		else
+			sleep $2
+			$LOADANDSHOWIMAGE 1 2 3 4 5 >> $LOG #unload image
+			$DMDT sb 0 2>> $LOG # switch back to standard output screen
+		fi
+	fi
+	trap 2
+
+	return 2> /dev/null
+
+};;
+
+-unload) {
+
+	trap '' 2
+
+	echo -ne "--- Stopping image display\n" | $TEE -i -a $LOG
+
+	if [[ "$TRAINVERSION" = *MHIG* ]]; then
+		LOADANDSHOWIMAGE="on -f mmx /net/mmx/eso/bin/apps/loadandshowimage"
+		export LIBIMG_CFGFILE=/net/mmx/etc/config/img.conf 2>> $LOG
+		$LOADANDSHOWIMAGE 1 2 3 4 5 >> $LOG #unload image
 		$DMRCClient -mv 2>> $LOG # switch back to standard output screen
-	fi
-else
-	LOADANDSHOWIMAGE="/net/mmx/eso/bin/apps/loadandshowimage"
-	export LIBIMG_CFGFILE=/net/mmx/etc/imgprocessing.cfg
-	#export LD_LIBRARY_PATH=/net/mmx/eso/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/app/armle/lib/dll
-	if [[ $5 = "SWDL" ]]; then
-		on -f mmx $LOADANDSHOWIMAGE ${3}${4}& >> $LOG
 	else
-		$LOADANDSHOWIMAGE ${3}${4}& >> $LOG
-	fi
-	$DMDT sc 0 -9 2>> $LOG # trigger display of image
-	#sleep 1
-	#/net/mmx/eso/bin/apps/dmdt ts 0 "/net/mmx/fs/sda0/screenshot_$4" | $TEE -a $LOG # take screenshot of dislpay output
-	if [[ $2 = 0 ]]; then
-		echo -ne "No end time for image set\n--- Stop image display with -unload\n" | $TEE -i -a $LOG
-	else
-		sleep $2
-		#export LD_LIBRARY_PATH=/net/mmx/eso/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/root/lib-target
+		LOADANDSHOWIMAGE="/net/mmx/eso/bin/apps/loadandshowimage"
+		export LIBIMG_CFGFILE=/net/mmx/etc/imgprocessing.cfg
 		$LOADANDSHOWIMAGE 1 2 3 4 5 >> $LOG #unload image
 		$DMDT sb 0 2>> $LOG # switch back to standard output screen
 	fi
-fi
-trap 2
 
-return 2> /dev/null
+	trap 2
 
-};;
+	return 2> /dev/null
 
-	-unload) {
+	};;
 
-trap '' 2
+		-ts) {
+	# Take a screenshot from screen 0 and dump to *.png file
+	# <time until screenshot> <file name appendix>
+	trap '' 2
 
-echo -ne "--- Stopping image display\n" | $TEE -i -a $LOG
+	if [[ "$TRAINVERSION" = *MHIG* ]]; then
+		echo -ne "No support for MHIG...\n" | $TEE -a $LOG
+		exit 0
+	fi
 
-if [[ "$TRAINVERSION" = *MHIG* ]]; then
-	LOADANDSHOWIMAGE="on -f mmx /net/mmx/eso/bin/apps/loadandshowimage"
-	export LIBIMG_CFGFILE=/net/mmx/etc/config/img.conf 2>> $LOG
-	$LOADANDSHOWIMAGE 1 2 3 4 5 >> $LOG #unload image
-	$DMRCClient -mv 2>> $LOG # switch back to standard output screen
-else
-	LOADANDSHOWIMAGE="/net/mmx/eso/bin/apps/loadandshowimage"
-	export LIBIMG_CFGFILE=/net/mmx/etc/imgprocessing.cfg
-	$LOADANDSHOWIMAGE 1 2 3 4 5 >> $LOG #unload image
-	$DMDT sb 0 2>> $LOG # switch back to standard output screen
-fi
+	if [ -z $2 ]; then
+		sleep 0
+	else
+		sleep $2
+	fi
 
-trap 2
+	ID=$(/net/rcc/usr/bin/date +%Y_%m_%d_%H_%M_%S)
 
-return 2> /dev/null
+	/net/mmx/eso/bin/apps/dmdt ts 0 "/net/mmx/fs/sda0/SCREENSHOT_${3}${ID}.png"
 
-};;
-
-	-ts) {
-# Take a screenshot from screen 0 and dump to *.png file
-# <time until screenshot> <file name appendix>
-trap '' 2
-
-if [[ "$TRAINVERSION" = *MHIG* ]]; then
-	echo -ne "No support for MHIG...\n" | $TEE -a $LOG
-	exit 0
-fi
-
-if [ -z $2 ]; then
-	sleep 0
-else
-	sleep $2
-fi
-
-ID=$(/net/rcc/usr/bin/date +%Y_%m_%d_%H_%M_%S)
-
-/net/mmx/eso/bin/apps/dmdt ts 0 "/net/mmx/fs/sda0/SCREENSHOT_${3}${ID}.png"
-
-return 2> /dev/null
+	return 2> /dev/null
 
 };;
 
